### ISSUE TITLE
Brosse tes dents

### ISSUE THREAD

**Issue by brunopc-net** [eurojulien/LOG320-TP3#2]
tu pus dla yeule

**Comment by eurojulien** [comment]
tu sens des fesses, pi je dis rien

**Comment by aflibottesavoie** [comment]
y'en a un qui pu dla yeule, l'autre sens des fesse, et moi je suis ici et j'espère très fort qu'il n'existe pas de liens entre vos odeurs déplaisantes ! XD

**Comment by eurojulien** [comment]
Te con

Julien Drolet-Noël

Si la santé vous intéresse !
http://eurojulien.bodybyvi.com/fr/index.html

Si la tranquillité vous tient a cœur 
http://sentierdudomaine.com/
